

type: discrete # options: continuous, discrete

discrete:
  beta_scheduler: cosine
  timesteps: 1000
  set_lr: 0.0001
  config_scheduler: CosineAnnealingLR
  min_snr_loss: True
  min_snr_gamma: 5.0

continuous:
  noise_schedule: karras
  min_snr_loss_weight: false
  min_snr_gamma: 5
  set_lr: 0.00001
  config_scheduler: CosineAnnealingLR