type: tar # tar or h5

tar:
  dataset: /work/bnovak/projects/sequence2ensemble/lammps_data/combined_data/latents_data
  batch_size: 16
  num_workers: 0
  prefetch_factor: null
  ionic_strength: 150
  train_size: 11_420_000 # estimated from num_tar_files * 10_000
  val_size: 2_450_000 # estimated from num_tar_files * 10_000

h5:
  train: /home/borna/ionic_strength_data/train.csv
  validation: /home/borna/ionic_strength_data/validation.csv
  test: /home/borna/ionic_strength_data/validation.csv
  