type: h5 # tar or h5

tar:
  dataset: /home/borna/packages/starling/starling/data/data

h5:
  train: /home/borna/ionic_strength_data/train.csv
  validation: /home/borna/ionic_strength_data/validation.csv
  test: /home/borna/ionic_strength_data/validation.csv

batch_size: 32
early_batch_size: 128
num_workers: 8
prefetch_factor: 5
sequence_context: finches_row_norm # Options: finches, finches_row_norm, finches_frob_norm