type: h5 # tar or h5

tar:
  dataset: /home/borna/packages/starling/starling/data/data

h5:
  train: /work/bnovak/projects/sequence2ensemble/lammps_data/20mM_data/train_test_val_splits/train_latents.csv
  validation: /work/bnovak/projects/sequence2ensemble/lammps_data/20mM_data/train_test_val_splits/validation_latents.csv
  test: /work/bnovak/projects/sequence2ensemble/lammps_data/20mM_data/train_test_val_splits/test_latents.csv

batch_size: 32
early_batch_size: 128
num_workers: 8
prefetch_factor: 2