cuda: 1
num_nodes: 1
num_workers: 8
num_epochs: 50
gradient_clip_val: 1.0
output_path: 20mM_model
project_name: starling-ionic-strength
checkpoint: /home/borna/.starling_weights/ddpm_no_encoder_weights.ckpt
fine_tune: true