_target_: starling.models.vae.VAE

model_type: Resnet18
in_channels: 1
latent_dim: 1
dimension: 384
loss_type: nll
weights_type: equal
KLD_weight: 0.00001
lr_scheduler: CosineAnnealingLR
set_lr: 0.00001
norm: instance
base: 64
optimizer: SGD
KLD_warmup_fraction: 0.005